apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity
  labels:
   env: dev
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: NotIn
            values:
            - us-east-1f
          - key: project
            operator: NotIn
            values:
            - roboshop
  containers:
  - name: nginx
    image: nginx       
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoExecute"

  
    